### ISSUE TITLE
Create Site Mockup

### ISSUE THREAD

**Issue by rap7or22** [rap7or22/WIRELESS-THUNDER#10]

**Comment by landerz** [comment]
Default landing page
![project1](https://user-images.githubusercontent.com/47302961/52450276-58bc9f00-2b08-11e9-81bc-a973d11c00e9.PNG)

**Comment by landerz** [comment]
Signed in user default page

![project1-2](https://user-images.githubusercontent.com/47302961/52450303-6e31c900-2b08-11e9-9802-ea40cbbfe9cc.PNG)

**Comment by landerz** [comment]
Logged in user video page

![project1-3](https://user-images.githubusercontent.com/47302961/52450324-83a6f300-2b08-11e9-94e4-54ccb9692a44.PNG)

**Comment by landerz** [comment]
Default video viewing page

![project1-4](https://user-images.githubusercontent.com/47302961/52450349-991c1d00-2b08-11e9-9978-bdf843b51fcf.PNG)

**Comment by landerz** [comment]
Default video page

![project1-4](https://user-images.githubusercontent.com/47302961/52450436-f7490000-2b08-11e9-8d98-4e952c2a2ade.PNG)

**Comment by landerz** [comment]
This was done in gomockingbird.com
